/** Deutsche Labels für Admin-Issue-Entwurf und LLM-Export (Epic 12). */
export const PRODUCT_FEEDBACK_LABELS: Record<string, string> = {
  NOT_WORKING: 'Funktioniert nicht',
  UNCLEAR: 'Unklar',
  MISSING_FEATURE: 'Fehlende Funktion',
  PRAISE: 'Positives Feedback',
  EASY: 'Leicht',
  MINOR_FRICTION: 'Mit kleinen Hürden',
  HARD: 'Schwierig',
  YES: 'Ja',
  PARTIAL: 'Teilweise',
  NO: 'Nein',
  HOST: 'Host',
  PARTICIPANT: 'Teilnehmende',
  GENERAL: 'Allgemein',
  POST_SESSION: 'Nach der Session',
  IN_APP: 'In der App',
  CONTINUED: 'Weiterarbeit war möglich',
  RETRIED: 'Erneuter Versuch war nötig',
  BLOCKED: 'Aufgabe konnte nicht abgeschlossen werden',
  JOIN: 'Sessionbeitritt',
  ORIENTATION: 'Orientierung',
  ANSWER: 'Antwortabgabe',
  QA_OR_QUICKFEEDBACK: 'Q&A oder Blitzlicht',
  RESULTS: 'Ergebnisse',
  TECH: 'Technik oder Verbindung',
  ACCESSIBILITY: 'Barrierefreiheit',
  OTHER: 'Anderer Bereich',
  PREPARE_QUIZ: 'Quizvorbereitung',
  START_SESSION: 'Sessionstart',
  INVITE: 'Einladung',
  LIVE_CONTROL: 'Live-Steuerung',
  PDF_EXPORT: 'PDF oder Export',
  QUIZ_OR_ANSWER: 'Quizfrage oder Antwort',
  QA: 'Q&A',
  QUICK_FEEDBACK: 'Blitzlicht',
  RESULTS_OR_SCORE: 'Ergebnis oder Punkte',
  DISPLAY_OR_ACCESSIBILITY: 'Darstellung oder Barrierefreiheit',
  TECH_OR_CONNECTION: 'Technik oder Verbindung',
  QUIZ_LIBRARY_OR_EDITOR: 'Quiz-Sammlung oder Editor',
  SESSION_START_OR_INVITE: 'Sessionstart und Einladung',
  PDF_OR_EXPORT: 'PDF oder Export',
  HOME_OR_ORIENTATION: 'Start und Orientierung',
  HELP: 'Hilfe',
  HOME: 'Startseite',
  QUIZ_LIBRARY: 'Quiz-Sammlung',
  QUIZ_EDITOR: 'Quiz-Editor',
  SESSION_JOIN: 'Sessionbeitritt',
  SESSION_VOTE: 'Teilnahme',
  SESSION_HOST: 'Sessionsteuerung',
  SESSION_RESULTS: 'Ergebnisse',
  PHONE: 'Smartphone',
  TABLET: 'Tablet',
  DESKTOP: 'Computer',
  UNKNOWN: 'Nicht erkannt',
  NEW: 'Neu',
  REVIEWED: 'Geprüft',
  PLANNED: 'Geplant',
  RESOLVED: 'Behoben',
  DISCARDED: 'Nicht weiterverfolgt',
  CHROME: 'Chrome',
  FIREFOX: 'Firefox',
  SAFARI: 'Safari',
  EDGE: 'Edge',
  ACTIVE: 'Aktiv',
  LOBBY: 'Lobby',
  FINISHED: 'Beendet',
  QUIZ: 'Quiz',
  MIXED: 'Gemischt',
  XS: 'bis 10 Personen',
  S: '11–30 Personen',
  M: '31–80 Personen',
  L: '81–200 Personen',
  XL: 'über 200 Personen',
  de: 'Deutsch',
  en: 'Englisch',
  fr: 'Französisch',
  es: 'Spanisch',
  it: 'Italienisch',
};

export function productFeedbackLabel(value: string | null | undefined): string | null {
  if (!value) return null;
  return PRODUCT_FEEDBACK_LABELS[value] ?? value;
}
