import type { QaNlpCategory } from '@arsnova/shared-types';

export type QaNlpSeedSplit = 'train' | 'eval';
export type QaNlpSeedLocale = 'de' | 'en' | 'fr' | 'es' | 'it' | 'mixed';
export type QaNlpSeedTag = 'canonical' | 'short' | 'typo' | 'slang' | 'code-switch' | 'ambiguous';

export type QaNlpSeedExample = {
  readonly text: string;
  readonly category: QaNlpCategory;
  readonly split: QaNlpSeedSplit;
  readonly locale: QaNlpSeedLocale;
  readonly tags: readonly QaNlpSeedTag[];
};

/**
 * Kuratiertes Q&A-Seed-Set fuer Gatekeeper-Training und Evaluation (ADR-0032).
 * Synthetisch, aber hoersaalnah; keine personenbezogenen Texte.
 */
export const QA_NLP_SEED_EXAMPLES: readonly QaNlpSeedExample[] = [
  // --- content / train ---
  {
    text: 'Kommt der Median in der Klausur vor?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Was ist der Unterschied zwischen Mittelwert und Median?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Koennen Sie das Beispiel zur Standardabweichung noch einmal erklaeren?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Welche Definition von Varianz sollen wir lernen?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Ist Aufgabe 3 klausurrelevant?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical', 'short'],
  },
  {
    text: 'Wie beweist man die Aussage auf Folie 12?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Ich verstehe den Loesungsweg der Uebungsaufgabe nicht.',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Welche Formel gilt fuer die Normalverteilung?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Will the exam cover confidence intervals?',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Can you explain the difference between precision and recall?',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'What does this definition of overfitting mean?',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Is the proof on slide 18 required?',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'I do not understand the exercise solution.',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Which formula should we use for Bayes theorem?',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Est-ce que la mediane est au programme de l examen?',
    category: 'content',
    split: 'train',
    locale: 'fr',
    tags: ['canonical'],
  },
  {
    text: 'No entiendo el ejemplo de la varianza.',
    category: 'content',
    split: 'train',
    locale: 'es',
    tags: ['canonical'],
  },
  {
    text: 'La definizione sulla slide 9 e da imparare?',
    category: 'content',
    split: 'train',
    locale: 'it',
    tags: ['canonical'],
  },
  {
    text: 'Ist p-value dasselbe wie Irrtumswahrscheinlichkeit?',
    category: 'content',
    split: 'train',
    locale: 'mixed',
    tags: ['code-switch'],
  },

  // --- organization / train ---
  {
    text: 'Bis wann muss die Hausarbeit abgegeben werden?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'In welchem Raum findet die Nachholklausur statt?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Gibt es naechste Woche eine Vorlesung oder Faellt sie aus?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Wie melde ich mich fuer die Uebungsgruppe an?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Ist Anwesenheit in den Tutorien Pflicht?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Wann wird die Punkteliste veroeffentlicht?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Koennen wir die Abgabefrist verlaengern?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Welcher Zoom-Link gilt fuer morgen?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'When is the assignment deadline?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Which room is the exam in?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Is attendance mandatory next week?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'How do I register for a tutorial group?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Will the lecture be cancelled on Friday?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'When will the scores be published?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Quelle est la date limite du devoir?',
    category: 'organization',
    split: 'train',
    locale: 'fr',
    tags: ['canonical'],
  },
  {
    text: 'En que aula es el examen?',
    category: 'organization',
    split: 'train',
    locale: 'es',
    tags: ['canonical'],
  },
  {
    text: 'Quando viene pubblicato il punteggio?',
    category: 'organization',
    split: 'train',
    locale: 'it',
    tags: ['canonical'],
  },
  {
    text: 'Deadline fuer das assignment: ist das Freitag?',
    category: 'organization',
    split: 'train',
    locale: 'mixed',
    tags: ['code-switch'],
  },

  // --- technical / train ---
  {
    text: 'Das WLAN im Hoersaal ist gerade tot.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical', 'slang'],
  },
  {
    text: 'Die PDF der Folien laedt nicht.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Ich hoere das Mikrofon nicht.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Der Login im Moodle schlaegt fehl.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Die Folien sind in der Praesentation nicht sichtbar.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Mein Browser zeigt die Abstimmung nicht an.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Der Stream ruckelt und das Audio faellt aus.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'QR-Code zum Join geht nicht.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical', 'short'],
  },
  {
    text: 'The slides PDF will not download.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'I cannot hear the microphone.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Wi-Fi in the lecture hall is down.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Moodle login fails with an error.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'The live stream has no audio.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'The voting page does not load in my browser.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Le PDF des slides ne se telecharge pas.',
    category: 'technical',
    split: 'train',
    locale: 'fr',
    tags: ['canonical'],
  },
  {
    text: 'No se oye el microfono.',
    category: 'technical',
    split: 'train',
    locale: 'es',
    tags: ['canonical'],
  },
  {
    text: 'Il Wi-Fi dell aula non funziona.',
    category: 'technical',
    split: 'train',
    locale: 'it',
    tags: ['canonical'],
  },
  {
    text: 'Browser crash beim Join, QR geht nicht.',
    category: 'technical',
    split: 'train',
    locale: 'mixed',
    tags: ['code-switch'],
  },

  // --- eval canonical ---
  {
    text: 'Ist die Herleitung auf Folie 7 pruefungsrelevant?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Koennen Sie den Begriff Konfidenzintervall noch einmal definieren?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Does the exam include hypothesis tests?',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Please explain the worked example again.',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Wann ist die Abgabefrist fuer das Projekt?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'In welchem Hoersaal schreiben wir die Klausur?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'When is the next tutorial session?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Do we need to register for the exam today?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Die Folien als PDF oeffnen sich nicht.',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Ich bekomme keinen Ton vom Mikro.',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['canonical', 'slang'],
  },
  {
    text: 'The lecture Wi-Fi dropped out.',
    category: 'technical',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'The quiz page is blank in Safari.',
    category: 'technical',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },

  // --- eval typos / short / code-switch ---
  {
    text: 'Klaustur: kommt Median vor?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['typo', 'short'],
  },
  {
    text: 'exampel solution nochmal erklaeren?',
    category: 'content',
    split: 'eval',
    locale: 'mixed',
    tags: ['typo', 'code-switch'],
  },
  {
    text: 'Abgebefrist bis wann?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['typo', 'short'],
  },
  {
    text: 'which romm for the exam?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['typo', 'short'],
  },
  {
    text: 'WLAN tot, slides laden nicht',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['short', 'slang'],
  },
  {
    text: 'micrpohne silent, pdf 404',
    category: 'technical',
    split: 'eval',
    locale: 'mixed',
    tags: ['typo', 'code-switch'],
  },

  // --- eval ambiguous: gold label is best effort; gatekeeper may mark uncertain ---
  {
    text: 'Das geht bei mir nicht.',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous', 'short'],
  },
  {
    text: 'Koennen wir das verschieben?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous', 'short'],
  },
  {
    text: 'Was genau meinten Sie damit?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous', 'short'],
  },
];

export function qaNlpSeedBySplit(split: QaNlpSeedSplit): QaNlpSeedExample[] {
  return QA_NLP_SEED_EXAMPLES.filter((example) => example.split === split);
}
