import type { QaNlpCategory } from '@arsnova/shared-types';

export type QaNlpSeedSplit = 'train' | 'eval';
export const QA_NLP_SEED_LOCALES = ['de', 'en', 'fr', 'es', 'it', 'mixed'] as const;
export type QaNlpSeedLocale = (typeof QA_NLP_SEED_LOCALES)[number];
export const QA_NLP_SEED_TAGS = [
  'canonical',
  'short',
  'typo',
  'slang',
  'code-switch',
  'ambiguous',
] as const;

export type QaNlpSeedTag = (typeof QA_NLP_SEED_TAGS)[number];

export type QaNlpSeedExample = {
  readonly text: string;
  readonly category: QaNlpCategory;
  readonly split: QaNlpSeedSplit;
  readonly locale: QaNlpSeedLocale;
  readonly tags: readonly QaNlpSeedTag[];
};

/**
 * Kuratiertes Q&A-Seed-Set fuer Gatekeeper-Training und Evaluation (ADR-0032).
 * Synthetisch, aber hoersaalnah; keine personenbezogenen Texte.
 */
export const QA_NLP_SEED_EXAMPLES: readonly QaNlpSeedExample[] = [
  // --- content / train ---
  {
    text: 'Kommt der Median in der Klausur vor?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Was ist der Unterschied zwischen Mittelwert und Median?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Koennen Sie das Beispiel zur Standardabweichung noch einmal erklaeren?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Welche Definition von Varianz sollen wir lernen?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Ist Aufgabe 3 klausurrelevant?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical', 'short'],
  },
  {
    text: 'Wie beweist man die Aussage auf Folie 12?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Ich verstehe den Loesungsweg der Uebungsaufgabe nicht.',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Welche Formel gilt fuer die Normalverteilung?',
    category: 'content',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Will the exam cover confidence intervals?',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Can you explain the difference between precision and recall?',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'What does this definition of overfitting mean?',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Is the proof on slide 18 required?',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'I do not understand the exercise solution.',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Which formula should we use for Bayes theorem?',
    category: 'content',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Est-ce que la mediane est au programme de l examen?',
    category: 'content',
    split: 'train',
    locale: 'fr',
    tags: ['canonical'],
  },
  {
    text: 'No entiendo el ejemplo de la varianza.',
    category: 'content',
    split: 'train',
    locale: 'es',
    tags: ['canonical'],
  },
  {
    text: 'La definizione sulla slide 9 e da imparare?',
    category: 'content',
    split: 'train',
    locale: 'it',
    tags: ['canonical'],
  },
  {
    text: 'Ist p-value dasselbe wie Irrtumswahrscheinlichkeit?',
    category: 'content',
    split: 'train',
    locale: 'mixed',
    tags: ['code-switch'],
  },

  // --- organization / train ---
  {
    text: 'Bis wann muss die Hausarbeit abgegeben werden?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'In welchem Raum findet die Nachholklausur statt?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Gibt es naechste Woche eine Vorlesung oder Faellt sie aus?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Wie melde ich mich fuer die Uebungsgruppe an?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Ist Anwesenheit in den Tutorien Pflicht?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Wann wird die Punkteliste veroeffentlicht?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Koennen wir die Abgabefrist verlaengern?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Welcher Zoom-Link gilt fuer morgen?',
    category: 'organization',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'When is the assignment deadline?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Which room is the exam in?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Is attendance mandatory next week?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'How do I register for a tutorial group?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Will the lecture be cancelled on Friday?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'When will the scores be published?',
    category: 'organization',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Quelle est la date limite du devoir?',
    category: 'organization',
    split: 'train',
    locale: 'fr',
    tags: ['canonical'],
  },
  {
    text: 'En que aula es el examen?',
    category: 'organization',
    split: 'train',
    locale: 'es',
    tags: ['canonical'],
  },
  {
    text: 'Quando viene pubblicato il punteggio?',
    category: 'organization',
    split: 'train',
    locale: 'it',
    tags: ['canonical'],
  },
  {
    text: 'Deadline fuer das assignment: ist das Freitag?',
    category: 'organization',
    split: 'train',
    locale: 'mixed',
    tags: ['code-switch'],
  },

  // --- technical / train ---
  {
    text: 'Das WLAN im Hoersaal ist gerade tot.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical', 'slang'],
  },
  {
    text: 'Die PDF der Folien laedt nicht.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Ich hoere das Mikrofon nicht.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Der Login im Moodle schlaegt fehl.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Die Folien sind in der Praesentation nicht sichtbar.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Mein Browser zeigt die Abstimmung nicht an.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Der Stream ruckelt und das Audio faellt aus.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'QR-Code zum Join geht nicht.',
    category: 'technical',
    split: 'train',
    locale: 'de',
    tags: ['canonical', 'short'],
  },
  {
    text: 'The slides PDF will not download.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'I cannot hear the microphone.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Wi-Fi in the lecture hall is down.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Moodle login fails with an error.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'The live stream has no audio.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'The voting page does not load in my browser.',
    category: 'technical',
    split: 'train',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Le PDF des slides ne se telecharge pas.',
    category: 'technical',
    split: 'train',
    locale: 'fr',
    tags: ['canonical'],
  },
  {
    text: 'No se oye el microfono.',
    category: 'technical',
    split: 'train',
    locale: 'es',
    tags: ['canonical'],
  },
  {
    text: 'Il Wi-Fi dell aula non funziona.',
    category: 'technical',
    split: 'train',
    locale: 'it',
    tags: ['canonical'],
  },
  {
    text: 'Browser crash beim Join, QR geht nicht.',
    category: 'technical',
    split: 'train',
    locale: 'mixed',
    tags: ['code-switch'],
  },

  // --- eval canonical ---
  {
    text: 'Ist die Herleitung auf Folie 7 pruefungsrelevant?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Koennen Sie den Begriff Konfidenzintervall noch einmal definieren?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Does the exam include hypothesis tests?',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Please explain the worked example again.',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Wann ist die Abgabefrist fuer das Projekt?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'In welchem Hoersaal schreiben wir die Klausur?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'When is the next tutorial session?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Do we need to register for the exam today?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Die Folien als PDF oeffnen sich nicht.',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Ich bekomme keinen Ton vom Mikro.',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['canonical', 'slang'],
  },
  {
    text: 'The lecture Wi-Fi dropped out.',
    category: 'technical',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'The quiz page is blank in Safari.',
    category: 'technical',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },

  // --- eval typos / short / code-switch ---
  {
    text: 'Klaustur: kommt Median vor?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['typo', 'short'],
  },
  {
    text: 'exampel solution nochmal erklaeren?',
    category: 'content',
    split: 'eval',
    locale: 'mixed',
    tags: ['typo', 'code-switch'],
  },
  {
    text: 'Abgebefrist bis wann?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['typo', 'short'],
  },
  {
    text: 'which romm for the exam?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['typo', 'short'],
  },
  {
    text: 'WLAN tot, slides laden nicht',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['short', 'slang'],
  },
  {
    text: 'micrpohne silent, pdf 404',
    category: 'technical',
    split: 'eval',
    locale: 'mixed',
    tags: ['typo', 'code-switch'],
  },

  // --- eval ambiguous: gold label is best effort; gatekeeper may mark uncertain ---
  {
    text: 'Das geht bei mir nicht.',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous', 'short'],
  },
  {
    text: 'Koennen wir das verschieben?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous', 'short'],
  },
  {
    text: 'Was genau meinten Sie damit?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous', 'short'],
  },

  // --- eval slice 3: canonical DE/EN/FR/ES/IT ---
  {
    text: 'Was bedeutet der p-Wert in Aufgabe 2?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Wie lautet die Definition von Bias auf Folie 4?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Is regularization part of the exam?',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Can you repeat the Bayes example from the board?',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Pouvez-vous reexpliquer la variance?',
    category: 'content',
    split: 'eval',
    locale: 'fr',
    tags: ['canonical'],
  },
  {
    text: 'La formula de Bayes esta en el examen?',
    category: 'content',
    split: 'eval',
    locale: 'es',
    tags: ['canonical'],
  },
  {
    text: 'L esempio sulla slide 4 e da studiare?',
    category: 'content',
    split: 'eval',
    locale: 'it',
    tags: ['canonical'],
  },
  {
    text: 'Findet die Sprechstunde naechste Woche statt?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Wo gebe ich die Hausarbeit ab?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Is the makeup exam on campus or online?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Do we get an extension for the project?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Le cours de vendredi est-il annule?',
    category: 'organization',
    split: 'eval',
    locale: 'fr',
    tags: ['canonical'],
  },
  {
    text: 'Donde se entrega el trabajo?',
    category: 'organization',
    split: 'eval',
    locale: 'es',
    tags: ['canonical'],
  },
  {
    text: 'L esame e in quale aula?',
    category: 'organization',
    split: 'eval',
    locale: 'it',
    tags: ['canonical'],
  },
  {
    text: 'Der Beamer zeigt nur den Desktop, nicht die Folien.',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'Die Abstimmung laedt ewig.',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['canonical'],
  },
  {
    text: 'My laptop cannot join the session code.',
    category: 'technical',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'The QR code is too blurry to scan.',
    category: 'technical',
    split: 'eval',
    locale: 'en',
    tags: ['canonical'],
  },
  {
    text: 'Le micro ne fonctionne plus.',
    category: 'technical',
    split: 'eval',
    locale: 'fr',
    tags: ['canonical'],
  },
  {
    text: 'La pagina de votacion no carga.',
    category: 'technical',
    split: 'eval',
    locale: 'es',
    tags: ['canonical'],
  },
  {
    text: 'Il codice QR non si legge.',
    category: 'technical',
    split: 'eval',
    locale: 'it',
    tags: ['canonical'],
  },

  // --- eval slice 3: typo / short / slang / code-switch ---
  {
    text: 'Konfidnezintervall nochmal erklaeren',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['typo'],
  },
  {
    text: 'hypotesis test in der klaustur',
    category: 'content',
    split: 'eval',
    locale: 'mixed',
    tags: ['typo', 'code-switch'],
  },
  {
    text: 'defintion of overfiting bitte',
    category: 'content',
    split: 'eval',
    locale: 'mixed',
    tags: ['typo', 'code-switch'],
  },
  {
    text: 'Folie 12 beweis, ich kapiers nicht',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['typo', 'slang'],
  },
  {
    text: 'what is precisoin vs recal',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['typo'],
  },
  {
    text: 'Median klausurrelevant?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['short'],
  },
  {
    text: 'Folie 7 nochmal?',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['short'],
  },
  {
    text: 'Exam: Bayes?',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['short'],
  },
  {
    text: 'Ist overfitting dasselbe wie overtraining?',
    category: 'content',
    split: 'eval',
    locale: 'mixed',
    tags: ['code-switch'],
  },
  {
    text: 'Was ist der bias-variance tradeoff hier?',
    category: 'content',
    split: 'eval',
    locale: 'mixed',
    tags: ['code-switch'],
  },
  {
    text: 'Slide 9: was ist recall genau?',
    category: 'content',
    split: 'eval',
    locale: 'mixed',
    tags: ['code-switch'],
  },
  {
    text: 'Ich check den Loesungsweg null',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['slang'],
  },
  {
    text: 'the example is kinda confusing, can you redo it',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['slang'],
  },
  {
    text: 'Nachholklaustur welcher raum',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['typo', 'short'],
  },
  {
    text: 'deadlien for hausarbeit',
    category: 'organization',
    split: 'eval',
    locale: 'mixed',
    tags: ['typo', 'code-switch'],
  },
  {
    text: 'tutroium anmelden wie',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['typo', 'short'],
  },
  {
    text: 'when is the assigment due exaclty',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['typo'],
  },
  {
    text: 'Abgabe wann?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['short'],
  },
  {
    text: 'Raum Nummer?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['short'],
  },
  {
    text: 'Tutorium Pflicht?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['short'],
  },
  {
    text: 'Ist die deadline wirklich Freitag?',
    category: 'organization',
    split: 'eval',
    locale: 'mixed',
    tags: ['code-switch'],
  },
  {
    text: 'Welcher Zoom link gilt heute?',
    category: 'organization',
    split: 'eval',
    locale: 'mixed',
    tags: ['code-switch'],
  },
  {
    text: 'Office hours heute cancelled?',
    category: 'organization',
    split: 'eval',
    locale: 'mixed',
    tags: ['code-switch', 'short'],
  },
  {
    text: 'Koennen wir die Abgabe schieben?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['slang'],
  },
  {
    text: 'is class off on friday?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['slang'],
  },
  {
    text: 'Wlan im horsaal tot',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['typo', 'slang'],
  },
  {
    text: 'moodel login error 500',
    category: 'technical',
    split: 'eval',
    locale: 'mixed',
    tags: ['typo', 'code-switch'],
  },
  {
    text: 'mikrofon is silent again',
    category: 'technical',
    split: 'eval',
    locale: 'mixed',
    tags: ['typo', 'code-switch'],
  },
  {
    text: 'safari blank quizz page',
    category: 'technical',
    split: 'eval',
    locale: 'en',
    tags: ['typo'],
  },
  {
    text: 'PDF 404',
    category: 'technical',
    split: 'eval',
    locale: 'mixed',
    tags: ['short'],
  },
  {
    text: 'Join code geht nicht',
    category: 'technical',
    split: 'eval',
    locale: 'mixed',
    tags: ['short', 'code-switch'],
  },
  {
    text: 'Kein Ton',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['short'],
  },
  {
    text: 'Stream laggt, audio gone',
    category: 'technical',
    split: 'eval',
    locale: 'mixed',
    tags: ['code-switch', 'slang'],
  },
  {
    text: 'Browser crash on vote page',
    category: 'technical',
    split: 'eval',
    locale: 'en',
    tags: ['code-switch'],
  },
  {
    text: 'QR join failed, wifi down',
    category: 'technical',
    split: 'eval',
    locale: 'en',
    tags: ['code-switch', 'short'],
  },
  {
    text: 'Die App spinnt bei mir',
    category: 'technical',
    split: 'eval',
    locale: 'de',
    tags: ['slang'],
  },
  {
    text: 'voting page is totally broken',
    category: 'technical',
    split: 'eval',
    locale: 'en',
    tags: ['slang'],
  },

  // --- eval slice 3: ambiguous (Gold Best-Effort, nicht in F1) ---
  {
    text: 'Huh?',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['ambiguous', 'short'],
  },
  {
    text: 'Das war zu schnell.',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous'],
  },
  {
    text: 'Can we go back?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['ambiguous', 'short'],
  },
  {
    text: 'Ich habs nicht mitbekommen.',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous'],
  },
  {
    text: 'Same question as before.',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['ambiguous'],
  },
  {
    text: 'Geht das auch anders?',
    category: 'organization',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous', 'short'],
  },
  {
    text: 'Not sure what you mean.',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['ambiguous'],
  },
  {
    text: 'Bitte nochmal.',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous', 'short'],
  },
  {
    text: 'Why?',
    category: 'content',
    split: 'eval',
    locale: 'en',
    tags: ['ambiguous', 'short'],
  },
  {
    text: 'Das hilft mir nicht.',
    category: 'content',
    split: 'eval',
    locale: 'de',
    tags: ['ambiguous'],
  },
  {
    text: 'Is this important?',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['ambiguous', 'short'],
  },
  {
    text: 'Later please.',
    category: 'organization',
    split: 'eval',
    locale: 'en',
    tags: ['ambiguous', 'short'],
  },
];

export function qaNlpSeedBySplit(split: QaNlpSeedSplit): QaNlpSeedExample[] {
  return QA_NLP_SEED_EXAMPLES.filter((example) => example.split === split);
}

/** Gelabeltes Eval ohne `ambiguous` (Gold dort nur Best-Effort). */
export function qaNlpLabeledEvalExamples(): QaNlpSeedExample[] {
  return qaNlpSeedBySplit('eval').filter((example) => !example.tags.includes('ambiguous'));
}

export function qaNlpAmbiguousEvalExamples(): QaNlpSeedExample[] {
  return qaNlpSeedBySplit('eval').filter((example) => example.tags.includes('ambiguous'));
}

export function qaNlpEvalExamplesWithTag(tag: QaNlpSeedTag): QaNlpSeedExample[] {
  return qaNlpSeedBySplit('eval').filter((example) => example.tags.includes(tag));
}
