-- Stories 1.2g / 1.2h / 1.2j: MATCHING, ORDERING, CATEGORIZATION

ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'MATCHING';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'ORDERING';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'CATEGORIZATION';

ALTER TABLE "Question"
ADD COLUMN IF NOT EXISTS "matchingPairs" JSONB,
ADD COLUMN IF NOT EXISTS "orderingItems" JSONB,
ADD COLUMN IF NOT EXISTS "categories" JSONB,
ADD COLUMN IF NOT EXISTS "categorizationItems" JSONB;

ALTER TABLE "Vote"
ADD COLUMN IF NOT EXISTS "matchingSelections" JSONB,
ADD COLUMN IF NOT EXISTS "orderingSequence" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "categorizationSelections" JSONB;
