/**
 * English-only “full tour” sample for the Markdown + KaTeX editor (toolbar: “Was geht?”).
 * Kept separate so UI strings stay localized while this reference stays stable in English.
 */
export const MARKDOWN_SHOWCASE_EN = [
  '## Markdown feature tour',
  '',
  'This template lists the **formatting options** you can use here. The preview updates on the right.',
  '',
  '### Headings',
  'Use levels 2–4 for section titles (recommended in content blocks).',
  '',
  '#### Heading level 4',
  '',
  '### Emphasis',
  '**Bold**, *italic*, and `inline code` in a sentence.',
  '',
  '### Lists',
  '',
  '**Bullet list**',
  '',
  '- First item',
  '- Second item',
  '  - Nested item',
  '',
  '**Ordered list**',
  '',
  '1. Step one',
  '2. Step two',
  '',
  '### Blockquote',
  '',
  '> A short quoted line. Use it for hints or citations.',
  '',
  '### Link',
  '',
  '[HTTPS link example](https://example.org)',
  '',
  '### Image (HTTPS)',
  '',
  'The short official **Wikipedia “W”** logo (from [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Wikipedia%27s_W.svg); trademark of the Wikimedia Foundation). **Click or tap the image** to open it in the lightbox (full-screen preview).',
  '',
  '![Wikipedia W logo](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Wikipedia%27s_W.svg/240px-Wikipedia%27s_W.svg.png)',
  '',
  '### Horizontal rule',
  '',
  '---',
  '',
  '### Math (KaTeX)',
  '',
  'Inline: $a^2 + b^2 = c^2$',
  '',
  'Block:',
  '',
  '$$',
  '\\int_0^1 x^2\\,dx = \\frac{1}{3}',
  '$$',
  '',
  '### Code',
  '',
  'Fenced block with an explicit language:',
  '',
  '```json',
  '{ "ok": true, "count": 42 }',
  '```',
  '',
  'Fenced block **without** a language tag (highlight defaults to Python in this app):',
  '',
  '```',
  'def greet(name: str) -> str:',
  '    return f"Hello, {name}!"',
  '```',
].join('\n');
