ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'SHORT_TEXT';

ALTER TABLE "Question"
ADD COLUMN IF NOT EXISTS "shortTextMaxLength" INTEGER,
ADD COLUMN IF NOT EXISTS "shortTextCaseSensitive" BOOLEAN NOT NULL DEFAULT false;