/**
 * Clientseitige Nickname-Listen pro Thema (Story 3.2). Mind. 50 Einträge pro Thema.
 *
 * Hinweis i18n: DE ist Quellsprache; für en/fr/es/it werden lokalisierte Listen genutzt.
 */
import type { NicknameTheme } from '@arsnova/shared-types';
import type { SupportedLocale } from '../../core/locale-from-path';

export const NICKNAME_LISTS: Record<NicknameTheme, readonly string[]> = {
  NOBEL_LAUREATES: [
    'Marie Curie',
    'Albert Einstein',
    'Ada Yonath',
    'Niels Bohr',
    'Max Planck',
    'Erwin Schrödinger',
    'Werner Heisenberg',
    'Paul Dirac',
    'Richard Feynman',
    'Linus Pauling',
    'Dorothy Hodgkin',
    'Maria Goeppert-Mayer',
    'Emmanuelle Charpentier',
    'Jennifer Doudna',
    'Frances Arnold',
    'Donna Strickland',
    'Gérard Mourou',
    'Arthur Ashkin',
    'Kip Thorne',
    'Barry Barish',
    'Rainer Weiss',
    'Peter Higgs',
    'François Englert',
    'Andre Geim',
    'Konstantin Novoselov',
    'Elizabeth Blackburn',
    'Carol Greider',
    'Jack Szostak',
    'Roger Kornberg',
    'Theodor Hänsch',
    'Roy Glauber',
    'John Hall',
    'Wolfgang Ketterle',
    'Eric Cornell',
    'Carl Wieman',
    'Steven Chu',
    'Claude Cohen-Tannoudji',
    'William Phillips',
    'Robert Laughlin',
    'Horst Störmer',
    'Daniel Tsui',
    'Gerardus t Hooft',
    'Martinus Veltman',
    'Robert Richardson',
    'Douglas Osheroff',
    'David Lee',
    'Bertram Brockhouse',
    'Clifford Shull',
    'Georges Charpak',
    'Russell Hulse',
    'Joseph Taylor',
    'Pierre-Gilles de Gennes',
    'Jerome Friedman',
    'Henry Kendall',
    'Richard Taylor',
    'Leon Lederman',
    'Melvin Schwartz',
    'Jack Steinberger',
    'Johannes Bednorz',
    'Karl Müller',
    'Ernst Ruska',
    'Gerd Binnig',
    'Heinrich Rohrer',
  ],
  KINDERGARTEN: [
    'Blauer Elefant',
    'Roter Drache',
    'Grüner Frosch',
    'Gelber Löwe',
    'Lila Delfin',
    'Oranger Fuchs',
    'Rosa Schmetterling',
    'Türkiser Wal',
    'Brauner Bär',
    'Schwarzer Panther',
    'Weißer Hase',
    'Grauer Wolf',
    'Goldene Auster',
    'Silberner Dodo',
    'Bunter Papagei',
    'Hellblauer Schwan',
    'Dunkelgrüne Schlange',
    'Zitronengelbe Biene',
    'Pfirsichfarbenes Pferd',
    'Mintgrüne Eidechse',
    'Korallenroter Krebs',
    'Himmelblauer Marienkäfer',
    'Olivgrüne Maus',
    'Beiger Igel',
    'Lachsfarbener Flamingo',
    'Lavendelblaue Eule',
    'Senfgelber Hahn',
    'Tannengrüner Biber',
    'Apfelgrüne Raupe',
    'Maulwurfsgrauer Hamster',
    'Kastanienbrauner Pavian',
    'Salbeigrünes Krokodil',
    'Terrakottafarbener Dachs',
    'Smaragdgrüne Libelle',
    'Safrangelber Vogel',
    'Indigoblauer Wal',
    'Magenta Schildkröte',
    'Petrolfarbener Fisch',
    'Vanillefarbenes Lamm',
    'Türkisfarbener Hund',
    'Korallenfarbene Katze',
    'Himmelblaue Giraffe',
    'Zitronengrünes Zebra',
    'Kupferfarbener Tiger',
    'Moosgrüner Koala',
    'Kirschroter Waschbär',
    'Saphirblaues Nilpferd',
    'Sandfarbenes Nashorn',
    'Jadegrünes Lama',
    'Sonnengelbe Ziege',
    'Nebelgrauer Widder',
    'Brombeerfarbene Kuh',
    'Tannengrünes Schwein',
    'Honigfarbener Eber',
    'Petrolblaue Ente',
    'Cremefarbene Taube',
    'Rubinfarbener Adler',
    'Mitternachtsblaue Fledermaus',
    'Pistaziengrüner Pfau',
    'Aprikosenfarbener Pinguin',
    'Malvenfarbener Truthahn',
    'Bernsteinfarbene Robbe',
    'Karamellfarbener Hai',
    'Eisblauer Kugelfisch',
    'Rosenholzfarbener Oktopus',
    'Mintfarbener Tintenfisch',
    'Safrangerote Garnele',
    'Lavendelfarbener Hummer',
    'Honiggelbe Schnecke',
    'Silbergraue Ameise',
    'Kastanienrote Spinne',
    'Olivfarbener Skorpion',
    'Türkisfarbene Mücke',
    'Sonnorange Fliege',
    'Pflaumenfarbener Käfer',
    'Karamellfarbene Schabe',
    'Regenbogenfarbiger Wurm',
    'Wolkengraue Ratte',
    'Meeresgrünes Eichhörnchen',
    'Kirschrosa Affe',
    'Azurfarbener Orang-Utan',
    'Waldgrüner Gorilla',
    'Perlmuttfarbener Bison',
    'Silberbraunes Reh',
    'Korallenfarbenes Känguru',
    'Nebelgraues Faultier',
    'Seegrüner Otter',
    'Veilchenfarbenes Stinktier',
    'Mondgraues Mammut',
    'Mahagonifarbener Wasserbüffel',
    'Sandbeiges Kamel',
    'Dünenfarbenes Trampeltier',
    'Schiefergrauer Esel',
    'Moosbrauner Elch',
    'Schneeweiße Gans',
    'Lagunenblaue Qualle',
    'Bernsteinfarbener Langhals',
    'Kirschroter T-Rex',
    'Stahlgrauer Ochse',
    'Honiggelbe Henne',
    'Schwarze Katze',
    'Goldgelbes Küken',
    'Silbernes Schlüpfküken',
    'Türkiser Assistenzhund',
    'Kobaltblauer Rabe',
    'Korallenfarbener Drachenkopf',
  ],
  PRIMARY_SCHOOL: [
    'Rotkäppchen',
    'Rumpelstilzchen',
    'Schneewittchen',
    'Dornröschen',
    'Aschenputtel',
    'Froschkönig',
    'Hänsel',
    'Gretel',
    'Rapunzel',
    'Frau Holle',
    'Schneeweißchen',
    'Rosenrot',
    'Der Wolf',
    'Die sieben Geißlein',
    'Der gestiefelte Kater',
    'Tischlein deck dich',
    'Goldesel',
    'Knüppel aus dem Sack',
    'Sterntaler',
    'Die Bremer Stadtmusikanten',
    'Der Hase',
    'Der Igel',
    'Der Fuchs',
    'Der Bär',
    'Das tapfere Schneiderlein',
    'Hans im Glück',
    'Der süße Brei',
    'Die Prinzessin auf der Erbse',
    'Des Kaisers neue Kleider',
    'Der Froschkönig',
    'Jorinde und Joringel',
    'Allerleirauh',
    'Die Gänsemagd',
    'Der Teufel mit den drei goldenen Haaren',
    'Die goldene Gans',
    'Brüderchen und Schwesterchen',
    'Der Eisenhans',
    'Der goldene Vogel',
    'Die sieben Raben',
    'Die zwölf Brüder',
    'König Drosselbart',
    'Märchen von einem der auszog',
    'Der Mond',
    'Die Sterntaler',
    'Schneeblume',
    'König Lindwurm',
    'Der kleine Däumling',
    'Die weiße Schlange',
    'Der Arme und der Reiche',
    'Das Wasser des Lebens',
    'Der Räuberbräutigam',
    'Fundevogel',
    'Die kluge Bauerntochter',
    'Der alte Großvater',
    'Die Wichtelmänner',
    'Die sieben Schwaben',
    'Simeliberg',
    'Der Trommler',
    'Die Kristallkugel',
  ],
  MIDDLE_SCHOOL: [
    'Kolumbus',
    'Amelia Earhart',
    'Marco Polo',
    'Neil Armstrong',
    'Jacques Cousteau',
    'Edmund Hillary',
    'Tenzing Norgay',
    'Roald Amundsen',
    'Robert Scott',
    'Ferdinand Magellan',
    'Vasco da Gama',
    'James Cook',
    'Lewis und Clark',
    'Sacagawea',
    'David Livingstone',
    'Mary Kingsley',
    'Ibn Battuta',
    'Zheng He',
    'Leif Erikson',
    'Erik der Rote',
    'Francis Drake',
    'Henry Hudson',
    'Amerigo Vespucci',
    'Hernán Cortés',
    'Francisco Pizarro',
    'Alexander von Humboldt',
    'Charles Darwin',
    'Alfred Wegener',
    'Thor Heyerdahl',
    'Yuri Gagarin',
    'Valentina Tereschkowa',
    'Sally Ride',
    'Buzz Aldrin',
    'John Glenn',
    'Alan Shepard',
    'Bruce McCandless',
    'Kalpana Chawla',
    'Mae Jemison',
    'Ellen Ochoa',
    'Superman',
    'Batman',
    'Wonder Woman',
    'Spider-Man',
    'Iron Man',
    'Captain America',
    'Black Widow',
    'Thor',
    'Hulk',
    'Black Panther',
    'Captain Marvel',
    'Ant-Man',
    'Wasp',
    'Doctor Strange',
    'Scarlet Witch',
    'Vision',
    'Falcon',
    'Winter Soldier',
    'Hawkeye',
    'Nick Fury',
    'Loki',
    'Groot',
    'Rocket',
    'Gamora',
    'Drax',
    'Star-Lord',
  ],
  HIGH_SCHOOL: [
    'Kant',
    'Noether',
    'Hawking',
    'Leibniz',
    'Newton',
    'Descartes',
    'Aristoteles',
    'Platon',
    'Sokrates',
    'Hegel',
    'Schopenhauer',
    'Nietzsche',
    'Wittgenstein',
    'Russell',
    'Popper',
    'Kuhn',
    'Feyerabend',
    'Hume',
    'Locke',
    'Berkeley',
    'Spinoza',
    'Rousseau',
    'Voltaire',
    'Montesquieu',
    'Hobbes',
    'Mill',
    'Bentham',
    'Rawls',
    'Habermas',
    'Arendt',
    'Heidegger',
    'Sartre',
    'Camus',
    'Simone de Beauvoir',
    'Foucault',
    'Derrida',
    'Deleuze',
    'Lacan',
    'Freud',
    'Jung',
    'Adorno',
    'Horkheimer',
    'Benjamin',
    'Marcuse',
    'Gadamer',
    'Ricoeur',
    'Levinas',
    'Jonas',
    'Apel',
    'Luhmann',
    'Weber',
    'Durkheim',
    'Simmel',
    'Mead',
    'Goffman',
    'Bourdieu',
    'Euclid',
    'Archimedes',
    'Pythagoras',
    'Galileo',
    'Kepler',
    'Copernicus',
    'Boyle',
    'Lavoisier',
    'Dalton',
    'Mendel',
    'Darwin',
    'Pasteur',
    'Koch',
    'Fleming',
  ],
} as const;

export const NICKNAME_LISTS_BY_LOCALE: Record<
  SupportedLocale,
  Record<NicknameTheme, readonly string[]>
> = {
  de: NICKNAME_LISTS,
  en: {
    NOBEL_LAUREATES: [
      'Marie Curie',
      'Albert Einstein',
      'Ada Yonath',
      'Niels Bohr',
      'Max Planck',
      'Erwin Schrödinger',
      'Werner Heisenberg',
      'Paul Dirac',
      'Richard Feynman',
      'Linus Pauling',
      'Dorothy Hodgkin',
      'Maria Goeppert-Mayer',
      'Emmanuelle Charpentier',
      'Jennifer Doudna',
      'Frances Arnold',
      'Donna Strickland',
      'Gérard Mourou',
      'Arthur Ashkin',
      'Kip Thorne',
      'Barry Barish',
      'Rainer Weiss',
      'Peter Higgs',
      'François Englert',
      'Andre Geim',
      'Konstantin Novoselov',
      'Elizabeth Blackburn',
      'Carol Greider',
      'Jack Szostak',
      'Roger Kornberg',
      'Theodor Hänsch',
      'Roy Glauber',
      'John Hall',
      'Wolfgang Ketterle',
      'Eric Cornell',
      'Carl Wieman',
      'Steven Chu',
      'Claude Cohen-Tannoudji',
      'William Phillips',
      'Robert Laughlin',
      'Horst Störmer',
      'Daniel Tsui',
      'Gerardus t Hooft',
      'Martinus Veltman',
      'Robert Richardson',
      'Douglas Osheroff',
      'David Lee',
      'Bertram Brockhouse',
      'Clifford Shull',
      'Georges Charpak',
      'Russell Hulse',
      'Joseph Taylor',
      'Pierre-Gilles de Gennes',
      'Jerome Friedman',
      'Henry Kendall',
      'Richard Taylor',
      'Leon Lederman',
      'Melvin Schwartz',
      'Jack Steinberger',
      'Johannes Bednorz',
      'Karl Müller',
      'Ernst Ruska',
      'Gerd Binnig',
      'Heinrich Rohrer',
    ],
    KINDERGARTEN: [
      'Blue elephant',
      'Red dragon',
      'Green frog',
      'Yellow lion',
      'Purple dolphin',
      'Orange fox',
      'Pink butterfly',
      'Turquoise whale',
      'Brown bear',
      'Black panther',
      'White rabbit',
      'Gray wolf',
      'Golden oyster',
      'Silver dodo',
      'Colorful parrot',
      'Light blue swan',
      'Dark green snake',
      'Lemon yellow bee',
      'Peach-colored horse',
      'Mint green lizard',
      'Coral crab',
      'Sky blue ladybug',
      'Olive green mouse',
      'Beige hedgehog',
      'Salmon colored flamingo',
      'Lavender blue owl',
      'Mustard yellow rooster',
      'Pine green beaver',
      'Apple green caterpillar',
      'Mole gray hamster',
      'Chestnut brown baboon',
      'Sage green crocodile',
      'Terracotta colored badger',
      'Emerald green dragonfly',
      'Saffron yellow bird',
      'Indigo blue whale',
      'Magenta turtle',
      'Teal colored fish',
      'Vanilla colored lamb',
      'Turquoise dog',
      'Coral cat',
      'Sky blue giraffe',
      'Lime green zebra',
      'Copper tiger',
      'Moss green koala',
      'Cherry red raccoon',
      'Sapphire blue hippo',
      'Sand colored rhino',
      'Jade green llama',
      'Sun yellow goat',
      'Misty gray ram',
      'Blackberry cow',
      'Fir green pig',
      'Honey colored boar',
      'Petrol blue duck',
      'Cream dove',
      'Ruby eagle',
      'Midnight blue bat',
      'Pistachio green peacock',
      'Apricot penguin',
      'Mauve turkey',
      'Amber seal',
      'Caramel shark',
      'Ice blue blowfish',
      'Rosewood octopus',
      'Mint squid',
      'Saffron red shrimp',
      'Lavender lobster',
      'Honey yellow snail',
      'Silver gray ant',
      'Chestnut red spider',
      'Olive scorpion',
      'Turquoise mosquito',
      'Sun orange fly',
      'Plum beetle',
      'Caramel cockroach',
      'Rainbow worm',
      'Cloud gray rat',
      'Sea green squirrel',
      'Cherry pink monkey',
      'Azure orangutan',
      'Forest green gorilla',
      'Pearl colored bison',
      'Silver brown deer',
      'Coral kangaroo',
      'Misty gray sloth',
      'Sea green otter',
      'Violet skunk',
      'Moon gray mammoth',
      'Mahogany water buffalo',
      'Sand beige camel',
      'Dune colored Bactrian camel',
      'Slate gray donkey',
      'Moss brown moose',
      'Snow white goose',
      'Lagoon blue jellyfish',
      'Amber sauropod',
      'Cherry red T-Rex',
      'Steel gray ox',
      'Honey yellow hen',
      'Black cat',
      'Golden chick',
      'Silver hatching chick',
      'Turquoise assistance dog',
      'Cobalt blue raven',
      'Coral dragon head',
    ],
    PRIMARY_SCHOOL: [
      'Little Red Riding Hood',
      'Rumpelstiltskin',
      'Snow White',
      'Sleeping Beauty',
      'Cinderella',
      'Frog Prince',
      'Hansel',
      'Gretel',
      'Rapunzel',
      'Mother Hulda',
      'Snow White',
      'Rose red',
      'The wolf',
      'The seven little kids',
      'Puss in Boots',
      'Set the table for yourself',
      'Cash cow',
      'Stick out of the bag',
      'Star thaler',
      'The Bremen Town Musicians',
      'The rabbit',
      'The hedgehog',
      'The fox',
      'The bear',
      'The brave little tailor',
      'Hans in luck',
      'The sweet porridge',
      'The Princess and the Pea',
      "The emperor's new clothes",
      'The Frog Prince',
      'Jorinde and Joringel',
      'Allerleirauh',
      'The goose girl',
      'The devil with three golden hairs',
      'The golden goose',
      'Little brother and sister',
      'Iron Hans',
      'The golden bird',
      'The seven ravens',
      'The twelve brothers',
      'King Thrushbeard',
      'Fairy tale about someone who moved out',
      'The moon',
      'The star thalers',
      'Snow Flower',
      'King Wyvern',
      'Little Thumbling',
      'The white snake',
      'The poor and the rich',
      'The water of life',
      'The robber groom',
      'Find bird',
      "The clever farmer's daughter",
      'The old grandfather',
      'The Secret Santa',
      'The seven Swabians',
      'Simeliberg',
      'The drummer',
      'The crystal ball',
    ],
    MIDDLE_SCHOOL: [
      'Columbus',
      'Amelia Earhart',
      'Marco Polo',
      'Neil Armstrong',
      'Jacques Cousteau',
      'Edmund Hillary',
      'Tenzing Norgay',
      'Roald Amundsen',
      'Robert Scott',
      'Ferdinand Magellan',
      'Vasco da Gama',
      'James Cook',
      'Lewis and Clark',
      'Sacagawea',
      'David Livingstone',
      'Mary Kingsley',
      'Ibn Battuta',
      'Zheng He',
      'Leif Erikson',
      'Eric the Red',
      'Francis Drake',
      'Henry Hudson',
      'Amerigo Vespucci',
      'Hernan Cortes',
      'Francisco Pizarro',
      'Alexander von Humboldt',
      'Charles Darwin',
      'Alfred Wegener',
      'Thor Heyerdahl',
      'Yuri Gagarin',
      'Valentina Tereshkova',
      'Sally Ride',
      'Buzz Aldrin',
      'John Glenn',
      'Alan Shepard',
      'Bruce McCandless',
      'Kalpana Chawla',
      'Mae Jemison',
      'Ellen Ochoa',
      'Superman',
      'Batman',
      'Wonder Woman',
      'Spider-Man',
      'Iron Man',
      'Captain America',
      'Black Widow',
      'Thor',
      'Hulk',
      'Black Panther',
      'Captain Marvel',
      'Ant Man',
      'Wasp',
      'Doctor Strange',
      'Scarlet Witch',
      'vision',
      'Falcon',
      'Winter Soldier',
      'Hawkeye',
      'Nick Fury',
      'Loki',
      'Groot',
      'Rocket',
      'Gamora',
      'Drax',
      'Star Lord',
    ],
    HIGH_SCHOOL: [
      'Kant',
      'Noether',
      'Hawking',
      'Leibniz',
      'Newton',
      'Descartes',
      'Aristoteles',
      'Platon',
      'Sokrates',
      'Hegel',
      'Schopenhauer',
      'Nietzsche',
      'Wittgenstein',
      'Russell',
      'Popper',
      'Kuhn',
      'Feyerabend',
      'Hume',
      'Locke',
      'Berkeley',
      'Spinoza',
      'Rousseau',
      'Voltaire',
      'Montesquieu',
      'Hobbes',
      'Mill',
      'Bentham',
      'Rawls',
      'Habermas',
      'Arendt',
      'Heidegger',
      'Sartre',
      'Camus',
      'Simone de Beauvoir',
      'Foucault',
      'Derrida',
      'Deleuze',
      'Lacan',
      'Freud',
      'Jung',
      'Adorno',
      'Horkheimer',
      'Benjamin',
      'Marcuse',
      'Gadamer',
      'Ricoeur',
      'Levinas',
      'Jonas',
      'Apel',
      'Luhmann',
      'Weber',
      'Durkheim',
      'Simmel',
      'Mead',
      'Goffman',
      'Bourdieu',
      'Euclid',
      'Archimedes',
      'Pythagoras',
      'Galileo',
      'Kepler',
      'Copernicus',
      'Boyle',
      'Lavoisier',
      'Dalton',
      'Mendel',
      'Darwin',
      'Pasteur',
      'Koch',
      'Fleming',
    ],
  } as const,
  fr: {
    NOBEL_LAUREATES: [
      'Marie Curie',
      'Albert Einstein',
      'Ada Yonath',
      'Niels Bohr',
      'Max Planck',
      'Erwin Schrödinger',
      'Werner Heisenberg',
      'Paul Dirac',
      'Richard Feynman',
      'Linus Pauling',
      'Dorothy Hodgkin',
      'Maria Goeppert-Mayer',
      'Emmanuelle Charpentier',
      'Jennifer Doudna',
      'Frances Arnold',
      'Donna Strickland',
      'Gérard Mourou',
      'Arthur Ashkin',
      'Kip Thorne',
      'Barry Barish',
      'Rainer Weiss',
      'Peter Higgs',
      'François Englert',
      'Andre Geim',
      'Konstantin Novoselov',
      'Elizabeth Blackburn',
      'Carol Greider',
      'Jack Szostak',
      'Roger Kornberg',
      'Theodor Hänsch',
      'Roy Glauber',
      'John Hall',
      'Wolfgang Ketterle',
      'Eric Cornell',
      'Carl Wieman',
      'Steven Chu',
      'Claude Cohen-Tannoudji',
      'William Phillips',
      'Robert Laughlin',
      'Horst Störmer',
      'Daniel Tsui',
      'Gerardus t Hooft',
      'Martinus Veltman',
      'Robert Richardson',
      'Douglas Osheroff',
      'David Lee',
      'Bertram Brockhouse',
      'Clifford Shull',
      'Georges Charpak',
      'Russell Hulse',
      'Joseph Taylor',
      'Pierre-Gilles de Gennes',
      'Jerome Friedman',
      'Henry Kendall',
      'Richard Taylor',
      'Leon Lederman',
      'Melvin Schwartz',
      'Jack Steinberger',
      'Johannes Bednorz',
      'Karl Müller',
      'Ernst Ruska',
      'Gerd Binnig',
      'Heinrich Rohrer',
    ],
    KINDERGARTEN: [
      'Éléphant bleu',
      'Dragon rouge',
      'Grenouille verte',
      'Lion jaune',
      'Dauphin violet',
      'Renard orange',
      'Papillon rose',
      'Baleine turquoise',
      'Ours brun',
      'Panthère noire',
      'Lapin blanc',
      'Loup gris',
      'Huître dorée',
      'Dodo argenté',
      'Perroquet coloré',
      'Cygne bleu clair',
      'Serpent vert foncé',
      'Abeille jaune citron',
      'Cheval couleur pêche',
      'Lézard vert menthe',
      'Crabe corail',
      'Coccinelle bleu ciel',
      'Souris vert olive',
      'Hérisson beige',
      'Flamant rose saumon',
      'Chouette bleu lavande',
      'Coq jaune moutarde',
      'Castor vert pin',
      'Chenille vert pomme',
      'Hamster gris taupe',
      'Babouin marron',
      'Crocodile vert sauge',
      'Blaireau couleur terre cuite',
      'Libellule vert émeraude',
      'Oiseau jaune safran',
      'Baleine bleue indigo',
      'Tortue magenta',
      'Poisson de couleur turquoise',
      'Agneau couleur vanille',
      'Chien turquoise',
      'Chat corail',
      'Girafe bleu ciel',
      'Zèbre vert citron',
      'Tigre cuivré',
      'Koala vert mousse',
      'Raton laveur rouge cerise',
      'Hippopotame bleu saphir',
      'Rhinocéros couleur sable',
      'Lama vert jade',
      'Chèvre jaune soleil',
      'Bélier gris brume',
      'Vache couleur mûre',
      'Cochon vert sapin',
      'Sanglier couleur miel',
      'Canard bleu pétrole',
      'Colombe crème',
      'Aigle rubis',
      'Chauve-souris bleu nuit',
      'Paon vert pistache',
      'Pingouin abricot',
      'Dinde mauve',
      'Phoque ambre',
      'Requin caramel',
      'Poisson-globe bleu glace',
      'Pieuvre bois de rose',
      'Calmar menthe',
      'Crevette rouge safran',
      'Homard lavande',
      'Escargot jaune miel',
      'Fourmi gris argent',
      'Araignée rouge châtaigne',
      'Scorpion olive',
      'Moustique turquoise',
      'Mouche orange soleil',
      'Scarabée prune',
      'Blatte caramel',
      'Ver arc-en-ciel',
      'Rat gris nuage',
      'Écureuil vert mer',
      'Singe rose cerise',
      'Orang-outan azur',
      'Gorille vert forêt',
      'Bison nacré',
      'Cerf brun argenté',
      'Kangourou corail',
      'Paresseux gris brume',
      'Loutre vert mer',
      'Moufette violette',
      'Mammouth gris lune',
      'Buffle aquatique acajou',
      'Chameau beige sable',
      'Chameau de Bactriane couleur dune',
      'Âne gris ardoise',
      'Élan brun mousse',
      'Oie blanche neige',
      'Méduse bleu lagon',
      'Dinosaure long-cou ambre',
      'T-Rex rouge cerise',
      'Bœuf gris acier',
      'Poule jaune miel',
      'Chat noir',
      'Poussin doré',
      "Poussin argenté à l'éclosion",
      "Chien d'assistance turquoise",
      'Corbeau bleu cobalt',
      'Tête de dragon corail',
    ],
    PRIMARY_SCHOOL: [
      'Le petit Chaperon rouge',
      'Peau de Rumplestilt',
      'Blanc comme neige',
      'La Belle au bois dormant',
      'Cendrillon',
      'Prince Grenouille',
      'Hansel',
      'Gretel',
      'Raiponce',
      'Mère Hulda',
      'Blanc comme neige',
      'Rose rouge',
      'Le loup',
      'Les sept petits enfants',
      'Le Chat Botté',
      'Mettez la table pour vous-même',
      'Vache à lait',
      'Sortez du sac',
      'Thaler étoile',
      'Les musiciens de Brême',
      'Le lapin',
      'Le hérisson',
      'Le renard',
      "L'ours",
      'Le courageux petit tailleur',
      'Hans a de la chance',
      'La bouillie sucrée',
      'La princesse et le petit pois',
      "Les nouveaux habits de l'empereur",
      'Le prince grenouille',
      'Jorinde et Joringel',
      'Allerleirauh',
      "La fille à l'oie",
      "Le diable aux trois cheveux d'or",
      "La poule aux œufs d'or",
      'Petit frère et petite soeur',
      'Hans de fer',
      "L'oiseau d'or",
      'Les sept corbeaux',
      'Les douze frères',
      'Roi Grivebarbe',
      "Conte de fées sur quelqu'un qui a déménagé",
      'La lune',
      'Les thalers étoiles',
      'Fleur de neige',
      'Roi Wyverne',
      'Petit Poucet',
      'Le serpent blanc',
      'Les pauvres et les riches',
      "L'eau de la vie",
      'Le marié voleur',
      'Trouver un oiseau',
      'La fille du fermier intelligent',
      'Le vieux grand-père',
      'Le Père Noël secret',
      'Les sept Souabes',
      'Simeliberg',
      'Le batteur',
      'La boule de cristal',
    ],
    MIDDLE_SCHOOL: [
      'Colomb',
      'Amélie Earhart',
      'Marco Polo',
      'Neil Armstrong',
      'Jacques Cousteau',
      'Edmond Hillary',
      'Tenzing Norgay',
      'Roald Amundsen',
      'Robert Scott',
      'Ferdinand Magellan',
      'Vasco de Gama',
      'James Cook',
      'Lewis et Clark',
      'Sacagawea',
      'David Livingstone',
      'Marie Kingsley',
      'Ibn Battouta',
      'Zheng He',
      'Leif Erikson',
      'Éric le Rouge',
      'Francis Drake',
      'Henri Hudson',
      'Amerigo Vespucci',
      'Hernan Cortés',
      'Francisco Pizarro',
      'Alexandre von Humboldt',
      'Charles Darwin',
      'Alfred Wegener',
      'Thor Heyerdahl',
      'Youri Gagarine',
      'Valentina Terechkova',
      'Sally Ride',
      'Buzz Aldrin',
      'John Glenn',
      'Alan Shepard',
      'Bruce McCandless',
      'Kalpana Chawla',
      'Mae Jemison',
      'Ellen Ochoa',
      'Superman',
      'Batman',
      'Wonder Woman',
      'Homme araignée',
      'Homme de fer',
      'Capitaine Amérique',
      'Veuve noire',
      'Thor',
      'Ponton',
      'Panthère noire',
      'Capitaine Marvel',
      "L'homme fourmi",
      'Guêpe',
      'Docteur étrange',
      'Sorcière écarlate',
      'Vision',
      'Faucon',
      "Soldat de l'Hiver",
      'Oeil de faucon',
      'Nick Fury',
      'Loki',
      'Groot',
      'Fusée',
      'Gamora',
      'Drax',
      'Seigneur des étoiles',
    ],
    HIGH_SCHOOL: [
      'Kant',
      'Noether',
      'Hawking',
      'Leibniz',
      'Newton',
      'Descartes',
      'Aristoteles',
      'Platon',
      'Sokrates',
      'Hegel',
      'Schopenhauer',
      'Nietzsche',
      'Wittgenstein',
      'Russell',
      'Popper',
      'Kuhn',
      'Feyerabend',
      'Hume',
      'Locke',
      'Berkeley',
      'Spinoza',
      'Rousseau',
      'Voltaire',
      'Montesquieu',
      'Hobbes',
      'Mill',
      'Bentham',
      'Rawls',
      'Habermas',
      'Arendt',
      'Heidegger',
      'Sartre',
      'Camus',
      'Simone de Beauvoir',
      'Foucault',
      'Derrida',
      'Deleuze',
      'Lacan',
      'Freud',
      'Jung',
      'Adorno',
      'Horkheimer',
      'Benjamin',
      'Marcuse',
      'Gadamer',
      'Ricoeur',
      'Levinas',
      'Jonas',
      'Apel',
      'Luhmann',
      'Weber',
      'Durkheim',
      'Simmel',
      'Mead',
      'Goffman',
      'Bourdieu',
      'Euclid',
      'Archimedes',
      'Pythagoras',
      'Galileo',
      'Kepler',
      'Copernicus',
      'Boyle',
      'Lavoisier',
      'Dalton',
      'Mendel',
      'Darwin',
      'Pasteur',
      'Koch',
      'Fleming',
    ],
  } as const,
  es: {
    NOBEL_LAUREATES: [
      'Marie Curie',
      'Albert Einstein',
      'Ada Yonath',
      'Niels Bohr',
      'Max Planck',
      'Erwin Schrödinger',
      'Werner Heisenberg',
      'Paul Dirac',
      'Richard Feynman',
      'Linus Pauling',
      'Dorothy Hodgkin',
      'Maria Goeppert-Mayer',
      'Emmanuelle Charpentier',
      'Jennifer Doudna',
      'Frances Arnold',
      'Donna Strickland',
      'Gérard Mourou',
      'Arthur Ashkin',
      'Kip Thorne',
      'Barry Barish',
      'Rainer Weiss',
      'Peter Higgs',
      'François Englert',
      'Andre Geim',
      'Konstantin Novoselov',
      'Elizabeth Blackburn',
      'Carol Greider',
      'Jack Szostak',
      'Roger Kornberg',
      'Theodor Hänsch',
      'Roy Glauber',
      'John Hall',
      'Wolfgang Ketterle',
      'Eric Cornell',
      'Carl Wieman',
      'Steven Chu',
      'Claude Cohen-Tannoudji',
      'William Phillips',
      'Robert Laughlin',
      'Horst Störmer',
      'Daniel Tsui',
      'Gerardus t Hooft',
      'Martinus Veltman',
      'Robert Richardson',
      'Douglas Osheroff',
      'David Lee',
      'Bertram Brockhouse',
      'Clifford Shull',
      'Georges Charpak',
      'Russell Hulse',
      'Joseph Taylor',
      'Pierre-Gilles de Gennes',
      'Jerome Friedman',
      'Henry Kendall',
      'Richard Taylor',
      'Leon Lederman',
      'Melvin Schwartz',
      'Jack Steinberger',
      'Johannes Bednorz',
      'Karl Müller',
      'Ernst Ruska',
      'Gerd Binnig',
      'Heinrich Rohrer',
    ],
    KINDERGARTEN: [
      'Elefante azul',
      'Dragón rojo',
      'Rana verde',
      'León amarillo',
      'Delfín morado',
      'Zorro naranja',
      'Mariposa rosa',
      'Ballena turquesa',
      'Oso pardo',
      'Pantera negra',
      'Conejo blanco',
      'Lobo gris',
      'Ostra dorada',
      'Dodo plateado',
      'Loro colorido',
      'Cisne azul claro',
      'Serpiente verde oscuro',
      'Abeja amarilla limón',
      'Caballo color melocotón',
      'Lagarto verde menta',
      'Cangrejo coralino',
      'Mariquita azul cielo',
      'Ratón verde oliva',
      'Erizo beige',
      'Flamenco color salmón',
      'Búho azul lavanda',
      'Gallo amarillo mostaza',
      'Castor verde pino',
      'Oruga verde manzana',
      'Hámster topo gris',
      'Babuino castaño',
      'Cocodrilo verde salvia',
      'Tejón color terracota',
      'Libélula verde esmeralda',
      'Pájaro amarillo azafrán',
      'Ballena azul índigo',
      'Tortuga magenta',
      'Pez de color verde azulado',
      'Cordero color vainilla',
      'Perro turquesa',
      'Gato coral',
      'Jirafa celeste',
      'Cebra verde lima',
      'Tigre cobrizo',
      'Koala verde musgo',
      'Mapache rojo cereza',
      'Hipopótamo azul zafiro',
      'Rinoceronte color arena',
      'Llama verde jade',
      'Cabra amarilla sol',
      'Carnero gris niebla',
      'Vaca color mora',
      'Cerdo verde abeto',
      'Jabalí color miel',
      'Pato azul petróleo',
      'Paloma color crema',
      'Águila rubí',
      'Murciélago azul medianoche',
      'Pavo real verde pistacho',
      'Pingüino albaricoque',
      'Pavo malva',
      'Foca ámbar',
      'Tiburón caramelo',
      'Pez globo azul hielo',
      'Pulpo palo de rosa',
      'Calamar menta',
      'Camarón rojo azafrán',
      'Langosta lavanda',
      'Caracol amarillo miel',
      'Hormiga gris plata',
      'Araña rojo castaña',
      'Escorpión oliva',
      'Mosquito turquesa',
      'Mosca naranja sol',
      'Escarabajo ciruela',
      'Cucaracha caramelo',
      'Gusano arcoíris',
      'Rata gris nube',
      'Ardilla verde mar',
      'Mono rosa cereza',
      'Orangután azur',
      'Gorila verde bosque',
      'Bisonte color perla',
      'Ciervo marrón plateado',
      'Canguro coral',
      'Perezoso gris niebla',
      'Nutria verde mar',
      'Mofeta violeta',
      'Mamut gris luna',
      'Búfalo de agua caoba',
      'Camello beige arena',
      'Camello bactriano color duna',
      'Burro gris pizarra',
      'Alce marrón musgo',
      'Oca blanca nieve',
      'Medusa azul laguna',
      'Dinosaurio ámbar de cuello largo',
      'T-Rex rojo cereza',
      'Buey gris acero',
      'Gallina amarilla miel',
      'Gato negro',
      'Pollito dorado',
      'Pollito plateado saliendo del cascarón',
      'Perro de asistencia turquesa',
      'Cuervo azul cobalto',
      'Cabeza de dragón coral',
    ],
    PRIMARY_SCHOOL: [
      'Caperucita roja',
      'Rumpelstiltskin',
      'Blanco como la nieve',
      'La Bella durmiente del bosque',
      'Cenicienta',
      'Príncipe rana',
      'Obsequiar',
      'Gretel',
      'Rapunzel',
      'Madre Hulda',
      'Blanco como la nieve',
      'Rosa roja',
      'El lobo',
      'Los siete niños pequeños',
      'El gato con botas',
      'Pon la mesa para ti',
      'Vaca de efectivo',
      'Sal de la bolsa',
      'Tálero estrella',
      'Los músicos de Bremen',
      'El conejo',
      'El erizo',
      'El zorro',
      'El oso',
      'El sastrecito valiente',
      'Hans de suerte',
      'La papilla dulce',
      'La princesa y el guisante',
      'El traje nuevo del emperador',
      'El príncipe rana',
      'Jorinde y Joringel',
      'Allerleirauh',
      'La chica ganso',
      'El diablo de los tres pelos de oro.',
      'La gallina de oro',
      'Hermano pequeño y hermana',
      'Hans de hierro',
      'El pájaro dorado',
      'Los siete cuervos',
      'Los doce hermanos',
      'Rey Tordobarba',
      'Cuento de hadas sobre alguien que se mudó',
      'La luna',
      'Los táleros estrella',
      'Flor de nieve',
      'Rey Wyvern',
      'Pequeño pulgarcito',
      'La serpiente blanca',
      'Los pobres y los ricos',
      'El agua de la vida',
      'El novio ladrón',
      'Encontrar pájaro',
      'La hija del granjero inteligente',
      'El viejo abuelo',
      'El Papá Noel secreto',
      'Los siete suabos',
      'Simeliberg',
      'El baterista',
      'La bola de cristal',
    ],
    MIDDLE_SCHOOL: [
      'Colón',
      'Amelia Earhart',
      'Marco Polo',
      'Neil Armstrong',
      'Jacques Cousteau',
      'Edmundo Hillary',
      'Tenzing Noruega',
      'Roald Amundsen',
      'Roberto Scott',
      'Fernando de Magallanes',
      'Vasco de Gama',
      'James Cook',
      'Lewis y Clark',
      'Sacagawea',
      'David Livingston',
      'María Kingsley',
      'Ibn Battuta',
      'Zheng He',
      'Leif Erikson',
      'Eric el rojo',
      'Francisco Drake',
      'Henry Hudson',
      'Amerigo Vespucci',
      'Hernán Cortés',
      'Francisco pizarro',
      'Alejandro de Humboldt',
      'Carlos Darwin',
      'Alfredo Wegener',
      'Thor Heyerdahl',
      'Yuri Gagarin',
      'Valentina Tereshkova',
      'Paseo sally',
      'Buzz Aldrin',
      'Juan Glenn',
      'Alan Shepard',
      'Bruce McCandless',
      'Kalpana Chawla',
      'Mae Jemison',
      'Elena Ochoa',
      'Superhombre',
      'Ordenanza',
      'Mujer maravilla',
      'Hombre araña',
      'Hombre de hierro',
      'Capitán América',
      'Viuda negra',
      'Thor',
      'Casco',
      'Pantera negra',
      'Capitana Marvel',
      'Hombre hormiga',
      'Avispa',
      'Doctor extraño',
      'Bruja escarlata',
      'Visión',
      'Halcón',
      'Soldado de invierno',
      'Ojo de halcón',
      'Nick Furia',
      'Loki',
      'Groot',
      'Cohete',
      'Gamora',
      'Drax',
      'Señor de las estrellas',
    ],
    HIGH_SCHOOL: [
      'Kant',
      'Noether',
      'Hawking',
      'Leibniz',
      'Newton',
      'Descartes',
      'Aristoteles',
      'Platon',
      'Sokrates',
      'Hegel',
      'Schopenhauer',
      'Nietzsche',
      'Wittgenstein',
      'Russell',
      'Popper',
      'Kuhn',
      'Feyerabend',
      'Hume',
      'Locke',
      'Berkeley',
      'Spinoza',
      'Rousseau',
      'Voltaire',
      'Montesquieu',
      'Hobbes',
      'Mill',
      'Bentham',
      'Rawls',
      'Habermas',
      'Arendt',
      'Heidegger',
      'Sartre',
      'Camus',
      'Simone de Beauvoir',
      'Foucault',
      'Derrida',
      'Deleuze',
      'Lacan',
      'Freud',
      'Jung',
      'Adorno',
      'Horkheimer',
      'Benjamin',
      'Marcuse',
      'Gadamer',
      'Ricoeur',
      'Levinas',
      'Jonas',
      'Apel',
      'Luhmann',
      'Weber',
      'Durkheim',
      'Simmel',
      'Mead',
      'Goffman',
      'Bourdieu',
      'Euclid',
      'Archimedes',
      'Pythagoras',
      'Galileo',
      'Kepler',
      'Copernicus',
      'Boyle',
      'Lavoisier',
      'Dalton',
      'Mendel',
      'Darwin',
      'Pasteur',
      'Koch',
      'Fleming',
    ],
  } as const,
  it: {
    NOBEL_LAUREATES: [
      'Marie Curie',
      'Albert Einstein',
      'Ada Yonath',
      'Niels Bohr',
      'Max Planck',
      'Erwin Schrödinger',
      'Werner Heisenberg',
      'Paul Dirac',
      'Richard Feynman',
      'Linus Pauling',
      'Dorothy Hodgkin',
      'Maria Goeppert-Mayer',
      'Emmanuelle Charpentier',
      'Jennifer Doudna',
      'Frances Arnold',
      'Donna Strickland',
      'Gérard Mourou',
      'Arthur Ashkin',
      'Kip Thorne',
      'Barry Barish',
      'Rainer Weiss',
      'Peter Higgs',
      'François Englert',
      'Andre Geim',
      'Konstantin Novoselov',
      'Elizabeth Blackburn',
      'Carol Greider',
      'Jack Szostak',
      'Roger Kornberg',
      'Theodor Hänsch',
      'Roy Glauber',
      'John Hall',
      'Wolfgang Ketterle',
      'Eric Cornell',
      'Carl Wieman',
      'Steven Chu',
      'Claude Cohen-Tannoudji',
      'William Phillips',
      'Robert Laughlin',
      'Horst Störmer',
      'Daniel Tsui',
      'Gerardus t Hooft',
      'Martinus Veltman',
      'Robert Richardson',
      'Douglas Osheroff',
      'David Lee',
      'Bertram Brockhouse',
      'Clifford Shull',
      'Georges Charpak',
      'Russell Hulse',
      'Joseph Taylor',
      'Pierre-Gilles de Gennes',
      'Jerome Friedman',
      'Henry Kendall',
      'Richard Taylor',
      'Leon Lederman',
      'Melvin Schwartz',
      'Jack Steinberger',
      'Johannes Bednorz',
      'Karl Müller',
      'Ernst Ruska',
      'Gerd Binnig',
      'Heinrich Rohrer',
    ],
    KINDERGARTEN: [
      'Elefante blu',
      'Drago rosso',
      'Rana verde',
      'Leone giallo',
      'Delfino viola',
      'Volpe arancione',
      'Farfalla rosa',
      'Balena turchese',
      'Orso bruno',
      'Pantera nera',
      'Coniglio bianco',
      'Lupo grigio',
      "Ostrica d'oro",
      'Dodo argentato',
      'Pappagallo colorato',
      'Cigno azzurro',
      'Serpente verde scuro',
      'Ape giallo limone',
      'Cavallo color pesca',
      'Lucertola verde menta',
      'Granchio di corallo',
      'Coccinella celeste',
      'Topo verde oliva',
      'Riccio beige',
      'Fenicottero color salmone',
      'Gufo blu lavanda',
      'Gallo giallo senape',
      'Castoro verde pino',
      'Bruco verde mela',
      'Criceto grigio talpa',
      'Babbuino marrone castano',
      'Coccodrillo verde salvia',
      'Tasso color terracotta',
      'Libellula verde smeraldo',
      'Uccellino giallo zafferano',
      'Balena blu indaco',
      'Tartaruga magenta',
      'Pesce color verde acqua',
      'Agnello color vaniglia',
      'Cane turchese',
      'Gatto corallo',
      'Giraffa celeste',
      'Zebra verde lime',
      'Tigre ramato',
      'Koala verde muschio',
      'Procione rosso ciliegia',
      'Ippopotamo blu zaffiro',
      'Rinoceronte color sabbia',
      'Lama verde giada',
      'Capra giallo sole',
      'Ariete grigio nebbia',
      'Mucca color mora',
      'Maiale verde abete',
      'Cinghiale color miele',
      'Anatra blu petrolio',
      'Colomba color crema',
      'Aquila rubino',
      'Pipistrello blu notte',
      'Pavone verde pistacchio',
      'Pinguino color albicocca',
      'Tacchino malva',
      'Foca color ambra',
      'Squalo color caramello',
      'Pesce palla blu ghiaccio',
      'Polpo color palissandro',
      'Calamaro color menta',
      'Gamberetto rosso zafferano',
      'Aragosta lavanda',
      'Lumaca giallo miele',
      'Formica grigio argento',
      'Ragno rosso castagna',
      'Scorpione oliva',
      'Zanzara turchese',
      'Mosca arancione sole',
      'Scarabeo prugna',
      'Scarafaggio caramello',
      'Verme arcobaleno',
      'Ratto grigio nuvola',
      'Scoiattolo verde mare',
      'Scimmia rosa ciliegia',
      'Orango azzurro',
      'Gorilla verde foresta',
      'Bisonte color perla',
      'Cervo bruno argentato',
      'Canguro corallo',
      'Bradipo grigio nebbia',
      'Lontra verde mare',
      'Moffetta viola',
      'Mammut grigio luna',
      'Bufalo acquatico mogano',
      'Cammello beige sabbia',
      'Cammello bactriano color dune',
      'Asino grigio ardesia',
      'Alce bruno muschio',
      'Oca bianca neve',
      'Medusa blu laguna',
      'Dinosauro ambrato dal collo lungo',
      'T-Rex rosso ciliegia',
      'Bue grigio acciaio',
      'Gallina giallo miele',
      'Gatto nero',
      'Pulcino dorato',
      'Pulcino argentato che si schiude',
      'Cane da assistenza turchese',
      'Corvo blu cobalto',
      'Testa di drago corallo',
    ],
    PRIMARY_SCHOOL: [
      'Cappuccetto Rosso',
      'Tremotino',
      'Bianco come la neve',
      'Bella addormentata',
      'Cenerentola',
      'Principe ranocchio',
      'Hansel',
      'Gretel',
      'Rapunzel',
      'Madre Hulda',
      'Bianco come la neve',
      'Rosa rossa',
      'Il lupo',
      'I sette capretti',
      'Il gatto con gli stivali',
      'Prepara la tavola per te',
      'Mucca da mungere',
      'Esci dalla borsa',
      'Tallero di stelle',
      'I musicanti di Brema',
      'Il coniglio',
      'Il riccio',
      'La volpe',
      "L'orso",
      'Il piccolo sarto coraggioso',
      'Hans nella fortuna',
      'Il porridge dolce',
      'La principessa sul pisello',
      "I vestiti nuovi dell'imperatore",
      'Il principe ranocchio',
      'Jorinde e Joringel',
      'Allerleirauh',
      'La ragazza delle oche',
      "Il diavolo dai tre capelli d'oro",
      "L'oca d'oro",
      'Fratellino e sorella',
      'Ferro Hans',
      "L'uccello d'oro",
      'I sette corvi',
      'I dodici fratelli',
      'Re Barbatordo',
      'Fiaba su qualcuno che se ne è andato',
      'La luna',
      'I talleri delle stelle',
      'Fiore di neve',
      'Re Viverna',
      'Piccolo Thumbling',
      'Il serpente bianco',
      'I poveri e i ricchi',
      "L'acqua della vita",
      'Lo sposo rapinatore',
      "Trova l'uccello",
      "La figlia dell'intelligente contadino",
      'Il vecchio nonno',
      'Il Babbo Natale segreto',
      'I sette Svevi',
      'Simeliberg',
      'Il batterista',
      'La sfera di cristallo',
    ],
    MIDDLE_SCHOOL: [
      'Colombo',
      'Amelia Earhart',
      'Marco Polo',
      'Neil Armstrong',
      'Jacques Cousteau',
      'Edmund Hillary',
      'Tenzing Norgay',
      'Roald Amundsen',
      'Roberto Scott',
      'Ferdinando Magellano',
      'Vasco da Gama',
      'James Cook',
      'Lewis e Clark',
      'Sacagawea',
      'David Livingstone',
      'Maria Kingsley',
      'Ibn Battuta',
      'Zheng He',
      'Leif Erikson',
      'Eric il Rosso',
      'Francesco Drake',
      'Henry Hudson',
      'Amerigo Vespucci',
      'Hernan Cortes',
      'Francesco Pizarro',
      'Alexander von Humboldt',
      'Carlo Darwin',
      'Alfred Wegener',
      'Thor Heyerdahl',
      'Yuri Gagarin',
      'Valentina Tereškova',
      'Sally Giro',
      'Buzz Aldrin',
      'John Glenn',
      'Alan Shepard',
      'Bruce McCandless',
      'Kalpana Chawla',
      'Mae Jemison',
      'Ellen Ochoa',
      'Superuomo',
      'Batman',
      'Donna Meraviglia',
      "L'Uomo Ragno",
      'Iron Man',
      'Capitan America',
      'Vedova Nera',
      'Thor',
      'Hulk',
      'Pantera Nera',
      'Capitan Marvel',
      "L'Uomo Formica",
      'Vespa',
      'Dottor Strange',
      'Strega Scarlatta',
      'Visione',
      'Falco',
      "Soldato d'inverno",
      'Occhio di Falco',
      'Nick Furia',
      'Loki',
      'Groot',
      'Razzo',
      'Gamora',
      'Drax',
      'Signore delle Stelle',
    ],
    HIGH_SCHOOL: [
      'Kant',
      'Noether',
      'Hawking',
      'Leibniz',
      'Newton',
      'Descartes',
      'Aristoteles',
      'Platon',
      'Sokrates',
      'Hegel',
      'Schopenhauer',
      'Nietzsche',
      'Wittgenstein',
      'Russell',
      'Popper',
      'Kuhn',
      'Feyerabend',
      'Hume',
      'Locke',
      'Berkeley',
      'Spinoza',
      'Rousseau',
      'Voltaire',
      'Montesquieu',
      'Hobbes',
      'Mill',
      'Bentham',
      'Rawls',
      'Habermas',
      'Arendt',
      'Heidegger',
      'Sartre',
      'Camus',
      'Simone de Beauvoir',
      'Foucault',
      'Derrida',
      'Deleuze',
      'Lacan',
      'Freud',
      'Jung',
      'Adorno',
      'Horkheimer',
      'Benjamin',
      'Marcuse',
      'Gadamer',
      'Ricoeur',
      'Levinas',
      'Jonas',
      'Apel',
      'Luhmann',
      'Weber',
      'Durkheim',
      'Simmel',
      'Mead',
      'Goffman',
      'Bourdieu',
      'Euclid',
      'Archimedes',
      'Pythagoras',
      'Galileo',
      'Kepler',
      'Copernicus',
      'Boyle',
      'Lavoisier',
      'Dalton',
      'Mendel',
      'Darwin',
      'Pasteur',
      'Koch',
      'Fleming',
    ],
  } as const,
};

export function getNicknameList(theme: NicknameTheme, locale: SupportedLocale): readonly string[] {
  const byLocaleForTheme = NICKNAME_LISTS_BY_LOCALE[locale] ?? NICKNAME_LISTS_BY_LOCALE.de;
  return byLocaleForTheme[theme] ?? NICKNAME_LISTS[theme] ?? [];
}
